export const timelineItems = [
    {
        date: 'September 2014 - June 2017',
        category: 'Education',
        title: "Bachelor's in Marketing Management",
        institution: 'ISCTE-IUL Lisbon, Portugal',
        description: '- Consumer Behaviour Psychology\n- Strategic Management\n- Marketing Communication',
        color: 'success.main',
    },
    {
        date: 'June 2016',
        category: 'Soul work',
        title: 'Erasmus+ Volunteer at a Youth Exchange in Georgia',
        description: 'Participation in workshops and debates regarding environmental issues in European countries',
        color: 'secondary.main',
    },
    {
        date: 'August 2017 - November 2017',
        category: 'Work',
        title: 'Front desk',
        institution: 'Easy Lisbon Hostel',
        description: 'Responsible for guest check-in, check-out and overall quality of stay.\n Managed online reservations across platforms (Booking, Expedia, HostelWorld).\n Initiated design work by creating a portfolio and a website.',
        color: 'secondary.main',
    },
    {
        date: 'November 2017 - May 2019',
        category: 'Work',
        title: 'Content & Social Media Manager',
        institution: 'Shiptimize (eCommerce operator)',
        description: 'Developed a content strategy (in Portuguese, English and Spanish) based on SEO and eCommerce metrics.\n Coordinated with development and marketing to ensure consistency in tone, visuals, and messaging',
        color: 'secondary.main',
    },
    {
        date: 'February 2019 - May 2019',
        category: 'Soul work',
        title: 'Volunteer English Teacher',
        institution: 'Speak Social Lisbon',
        description: 'Taught English to refugees and immigrants in Lisbon',
        color: 'secondary.main',
    },
    {
        date: 'June 2019 - August 2019',
        category: 'Soul work',
        title: 'Solo trip to Southeast Asia',
        description: 'Solo trip through Singapore, Malaysia, Thailand, Cambodia and Vietnam',
        color: 'secondary.main',
    },
    {
        date: 'September 2019 - May 2021',
        category: 'Education',
        title: "Master's in New Media Design",
        institution: 'Tilburg University, The Netherlands',
        description: '- UX & Usability Evaluation\n- Human Media Interaction Theory\n- Prototyping & Research',
        color: 'success.main',
    },
    {
        date: 'February 2020 - May 2021',
        category: 'Work',
        title: 'Student jobs',
        description: 'Delivery driver at Dominos Pizza\n Logistics Operator at H&M warehouse',
        color: 'secondary.main',
    },
    {
        date: 'September 2020 - May 2021',
        category: 'Education',
        title: "Outreaching Honors Program",
        institution: 'Tilburg University, The Netherlands',
        description: '- UX & Usability Evaluation\n- Human Media Interaction Theory\n- Prototyping & Research',
        color: 'success.main',
    },
    {
        date: 'May 2021 - January 2022',
        category: 'Soul work',
        title: 'International Volunteer with European Solidarity Corps (ESC)',
        description: "Led a team of volunteers and organised a series of entrepreneurship events across Hungary\n Collaborated in a multicultural team to plan content and communications for 'Respekt und Neugier Festival' (a music and arts festival in Berlin)\n Designed and facilitated workshops in a children's festival in Magdeburg \n Worked with children with special needs, refugees, and low-income families in Cairo",
        color: 'secondary.main',
    },
    {
        date: 'June 2021 - December 2022',
        category: 'Work',
        title: 'Portuguese teacher',
        institution: 'iTalki',
        description: 'Taught Portuguese to students online through grammar, reading and speaking exercises',
        color: 'primary.main',
    },
    {
        date: 'March 2022 - September 2022',
        category: 'Work',
        title: 'Communication Specialist',
        institution: 'ChibiPhoenix (gaming studio)',
        description: 'Led the design of landing pages for gaming products (Figma)\nCollected and analysed user engagement data (LinkedIn, Facebook) to create digital promotional assets (Photoshop, Canva, Adobe Premiere Pro)',
        color: 'primary.main',
    },
    {
        date: 'January 2023 - April 2023',
        category: 'Education',
        title: "Full Stack TypeScript Bootcamp",
        institution: 'School of Applied Technology Amsterdam (SALT)',
        description: 'Intensive training program with a focus on NodeJS, Express, HTML&CSS, React, under a test-driven development.',
        color: 'success.main',
    },
    {
        date: 'April 2023 - July 2023',
        category: 'Work',
        title: 'Freelance designer and fullstack developer',
        institution: 'Self-employed',
        description: 'Worked directly with clients to understand business goals and transform them into wireframes and prototypes (Figma)\nDeveloped functional and responsive web pages using TypeScript, React, and Tailwind',
        color: 'primary.main',
    },
    {
        date: 'July 2023 - Present',
        category: 'Work',
        title: 'Frontend Developer',
        institution: 'SaxoBank (investment bank)',
        description: 'Translated Figma designs into performant, accessible frontend components (e.g., news modules). Ensured robustness through unit and integration tests.\nParticipated in sprint ‘ceremonies’, including backlog grooming, standups, and retrospectives. Collaborated with designers to refine designs according to technical restrictions\nStack: TypeScript, React, Redux, Playwright, Jest',
        color: 'primary.main',
    },
];